language: python
dist: xenial
sudo: required
python:
- "3.7"
notifications:
  email:
    on_success: never
    on_failure: change
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bash
    - coreutils
cache:
  directories:
  - "/home/travis/.cache/pip"
before_install:
- pip3 install --upgrade pip
- pip3 install poetry
install:
- poetry install
script:
- poetry run tox
